### ISSUE TITLE
DeprecationWarning and DistributionNotFound issues with btcli

### ISSUE THREAD

**Issue by aniruddhsingh7901** [opentensor/developer-docs#324]
Expected Behavior:
The btcli --help command should display the help information without any errors related to deprecated packages or missing distributions
but showing this :-1: 

/usr/local/bin/btcli:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('bittensor==7.2.0', 'btcli')
Traceback (most recent call last):
  File "/usr/local/bin/btcli", line 4, in <module>
    __import__('pkg_resources').run_script('bittensor==7.2.0', 'btcli')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ansible_vault~=2.1' distribution was not found and is required by bittensor

**Comment by rajkaramchedu** [comment]
Please report this in the bittensor repo as this issue is about the btcli CLI.
